databaseChangeLog:
  - changeSet:
      id: 1.1.0
      author: Tadej Eker
      changes:
        - createTable:
            tableName: hist_claims
            columns:
              - column:
                  name: hist_id
                  type: bigint
                  autoIncrement: true
                  incrementBy: 1
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: id
                  type: bigint
              - column:
                  name: claim_id
                  type: varchar(255)
              - column:
                  name: event_date
                  type: timestamp
              - column:
                  name: notification_date
                  type: timestamp
              - column:
                  name: entry_date
                  type: timestamp
              - column:
                  name: contract_id
                  type: varchar(255)
              - column:
                  name: offer_id
                  type: varchar(255)
              - column:
                  name: account_id
                  type: varchar(255)
              - column:
                  name: type
                  type: varchar(255)
              - column:
                  name: coverage_id
                  type: varchar(255)
              - column:
                  name: status
                  type: varchar(255)
              - column:
                  name: product_id
                  type: varchar(255)
              - column:
                  name: product_description
                  type: varchar(255)
              - column:
                  name: insurance_id
                  type: varchar(255)
              - column:
                  name: without_coverage
                  type: boolean
              - column:
                  name: place_of_event
                  type: text
              - column:
                  name: description
                  type: text
              - column:
                  name: symass_id
                  type: varchar(255)
              - column:
                  name: version
                  type: integer
              - column:
                  name: created_at
                  type: timestamp
              - column:
                  name: created_by
                  type: varchar(255)
              - column:
                  name: updated_at
                  type: timestamp
              - column:
                  name: updated_by
                  type: varchar(255)
        - createTable:
            tableName: hist_claim_accounts
            columns:
              - column:
                  name: hist_id
                  type: bigint
                  autoIncrement: true
                  incrementBy: 1
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: id
                  type: bigint
              - column:
                  name: balance
                  type: decimal(19, 2)
              - column:
                  name: currency
                  type: char(3)
              - column:
                  name: type
                  type: varchar(255)
              - column:
                  name: claim_id
                  type: bigint
              - column:
                  name: version
                  type: integer
              - column:
                  name: created_at
                  type: timestamp
              - column:
                  name: created_by
                  type: varchar(255)
              - column:
                  name: updated_at
                  type: timestamp
              - column:
                  name: updated_by
                  type: varchar(255)
        - createTable:
            tableName: hist_claim_payments
            columns:
              - column:
                  name: hist_id
                  type: bigint
                  autoIncrement: true
                  incrementBy: 1
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: id
                  type: bigint
              - column:
                  name: claim_payment_id
                  type: varchar(255)
              - column:
                  name: amount
                  type: decimal(19, 2)
              - column:
                  name: currency
                  type: char(3)
              - column:
                  name: payment_reference
                  type: text
              - column:
                  name: receiver_id
                  type: varchar(255)
              - column:
                  name: receiver_type
                  type: varchar(255)
              - column:
                  name: entry_date
                  type: timestamp
              - column:
                  name: salesforce_id
                  type: varchar(255)
              - column:
                  name: symass_id
                  type: varchar(255)
              - column:
                  name: claim_id
                  type: bigint
              - column:
                  name: e2e_external_id
                  type: varchar(255)
              - column:
                  name: status
                  type: varchar(255)
              - column:
                  name: sent_to_payout_date
                  type: timestamp
              - column:
                  name: payment_date
                  type: timestamp
              - column:
                  name: returned_payment_date
                  type: timestamp
              - column:
                  name: version
                  type: integer
              - column:
                  name: created_at
                  type: timestamp
              - column:
                  name: created_by
                  type: varchar(255)
              - column:
                  name: updated_at
                  type: timestamp
              - column:
                  name: updated_by
                  type: varchar(255)
        - sqlFile:
            dbms: '!h2, postgresql'
            path: scripts/v1/claims_hist_fnc.sql
            relativeToChangelogFile: true
            splitStatements: false
        - sqlFile:
            dbms: '!h2, postgresql'
            path: scripts/v1/claims_hist_trigger.sql
            relativeToChangelogFile: true
            splitStatements: false
        - sqlFile:
            dbms: '!h2, postgresql'
            path: scripts/v1/claim_accounts_hist_fnc.sql
            relativeToChangelogFile: true
            splitStatements: false
        - sqlFile:
            dbms: '!h2, postgresql'
            path: scripts/v1/claim_accounts_hist_trigger.sql
            relativeToChangelogFile: true
            splitStatements: false
        - sqlFile:
            dbms: '!h2, postgresql'
            path: scripts/v1/claim_payments_hist_fnc.sql
            relativeToChangelogFile: true
            splitStatements: false
        - sqlFile:
            dbms: '!h2, postgresql'
            path: scripts/v1/claim_payments_hist_trigger.sql
            relativeToChangelogFile: true
            splitStatements: false
